//! What a served site needs from the webserver: its vhost, nginx's server-name
//! hash size, and .ddev/config.worktrees.yaml (hostnames plus one FPM daemon per
//! extra PHP version).

use std::path::PathBuf;

use super::ctx::Ctx;
use super::site;

/// Where a site's vhost goes, per webserver type. Ours carry no
/// #ddev-generated marker, so DDEV never overwrites them, and are prefixed so
/// they cannot collide with DDEV's own files.
pub fn vhost_file(ctx: &Ctx, name: &str) -> PathBuf {
    if ctx.env.is_nginx() {
        ctx.root
            .join(format!(".ddev/nginx_full/tryout-site-{name}.conf"))
    } else {
        ctx.root
            .join(format!(".ddev/apache/tryout-site-{name}.conf"))
    }
}

/// The http-level config sizing nginx's server-name hash — separate from the
/// vhosts, which are `server` blocks.
pub fn hash_config_file(ctx: &Ctx) -> PathBuf {
    ctx.root
        .join(".ddev/nginx_full/tryout-server-names-hash.conf")
}

/// Where the FPM master for a PHP version listens: DDEV's own for the project's
/// version, ours (under /run/php/, root-owned /run notwithstanding) otherwise.
pub fn fpm_socket(ctx: &Ctx, php: &str) -> String {
    if php == ctx.env.php_version {
        "/run/php-fpm.sock".into()
    } else {
        format!("/run/php/php-fpm-{php}.sock")
    }
}

/// A served site's vhost. nginx must pass `HTTPS $fcgi_https`, or PHP never
/// learns the request was TLS and TYPO3's secure session cookie never comes
/// back ("Please activate Cookies").
pub fn vhost(ctx: &Ctx, name: &str, php: &str) -> String {
    let docroot = format!("/var/www/html/TYPO3-Instances/{name}/public");
    let host = site::hostname(ctx, name);
    let db = site::database(name);
    let sock = fpm_socket(ctx, php);
    if ctx.env.webserver_type == "nginx-fpm" {
        format!(
            r#"# Generated by ddev tryout worktree serve {name} — edits will be overwritten.
server {{
    listen 80;
    listen 443 ssl;
    http2 on;
    server_name {host};
    ssl_certificate /etc/ssl/certs/master.crt;
    ssl_certificate_key /etc/ssl/certs/master.key;
    root {docroot};
    index index.php index.html;

    location / {{
        try_files $uri $uri/ /index.php$is_args$args;
    }}
    location ~ [^/]\.php(/|$) {{
        try_files $uri =404;
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param TRYOUT_SITE {name};
        fastcgi_param TYPO3_DB_DBNAME {db};
        # Without this PHP never learns the request arrived over TLS, so TYPO3
        # builds http:// URLs and its secure session cookie is never sent back —
        # the backend login then fails with "Please activate Cookies". DDEV's own
        # vhost sets the same parameter.
        fastcgi_param HTTPS $fcgi_https;
        fastcgi_pass unix:{sock};
    }}
}}
"#
        )
    } else {
        format!(
            r#"# Generated by ddev tryout worktree serve {name} — edits will be overwritten.
<VirtualHost *:80 *:443>
    ServerName {host}
    DocumentRoot {docroot}

    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/master.crt
    SSLCertificateKeyFile /etc/ssl/certs/master.key

    SetEnvIf X-Forwarded-Proto "https" HTTPS=on
    SetEnv TRYOUT_SITE {name}
    SetEnv TYPO3_DB_DBNAME {db}

    <Directory "{docroot}/">
        AllowOverride All
        Require all granted
    </Directory>

    # Overrides the global conf-enabled/php*-fpm.conf handler: sites-enabled is
    # read later and a FilesMatch inside a VirtualHost is more specific.
    <FilesMatch ".+\.ph(?:ar|p|tml)$">
        SetHandler "proxy:unix:{sock}|fcgi://localhost"
    </FilesMatch>

    ErrorLog /dev/stdout
    CustomLog /dev/stdout combined
</VirtualHost>
"#
        )
    }
}

pub fn write_vhost(ctx: &Ctx, name: &str, php: &str) -> std::io::Result<()> {
    let file = vhost_file(ctx, name);
    std::fs::create_dir_all(file.parent().expect("a vhost file has a directory"))?;
    std::fs::write(file, vhost(ctx, name, php))
}

/// nginx refuses to START when a server_name outgrows its hash bucket — taking
/// every site down. Size the bucket for the longest served name (the short form
/// plus the `.ddev.site` DDEV appends), doubling from 64 until it clears the
/// name plus nginx's per-entry overhead. None when nothing is served.
pub fn hash_config(short_hosts: &[String]) -> Option<String> {
    let longest = short_hosts
        .iter()
        .filter(|h| !h.is_empty())
        .map(|h| h.chars().count() + 11)
        .max()?;
    let mut size = 64;
    while size < longest + 24 {
        size *= 2;
    }
    Some(format!(
        "#ddev-generated\n# Generated by ddev tryout worktree serve — do not edit.\n\
# Sized for the longest served hostname ({longest} chars). Without this nginx\n\
# refuses to start once a name outgrows the default bucket, taking every site\n\
# with it.\nserver_names_hash_bucket_size {size};\n"
    ))
}

/// .ddev/config.worktrees.yaml for the served sites: their hostnames (so mkcert
/// covers them) and one FPM daemon per PHP version other than the project's.
/// None when nothing is served.
pub fn worktree_config(ctx: &Ctx) -> Option<String> {
    let names = site::served_names(ctx);
    if names.is_empty() {
        return None;
    }
    let mut s = String::from(
        "#ddev-silent-no-warn\n# Generated by ddev tryout worktree serve — do not edit.\n\
# Hostnames must be registered here so mkcert includes them in the cert.\n\nadditional_hostnames:\n",
    );
    for n in &names {
        s.push_str(&format!("  - {}\n", site::hostname_short(ctx, n)));
    }
    let mut phps: Vec<String> = names
        .iter()
        .map(|n| site::php_version(ctx, n))
        .filter(|p| !p.is_empty() && *p != ctx.env.php_version)
        .collect();
    phps.sort();
    phps.dedup();
    if !phps.is_empty() {
        s.push_str("\nweb_extra_daemons:\n");
        for v in phps {
            s.push_str(&format!(
                "  - name: tryout-php-{v}\n    command: \"/var/www/html/.ddev/tryout/tryout __fpm {v}\"\n    directory: /var/www/html\n"
            ));
        }
    }
    Some(s)
}

/// Rewrite config.worktrees.yaml and the hash config from what is served now;
/// both go when nothing is.
pub fn write_worktree_config(ctx: &Ctx) -> std::io::Result<()> {
    let hosts: Vec<String> = site::served_names(ctx)
        .iter()
        .map(|n| site::hostname_short(ctx, n))
        .collect();
    let hash = hash_config_file(ctx);
    match hash_config(&hosts) {
        Some(c) => {
            std::fs::create_dir_all(hash.parent().expect("has a directory"))?;
            std::fs::write(&hash, c)?;
        }
        None => {
            let _ = std::fs::remove_file(&hash);
        }
    }
    match worktree_config(ctx) {
        Some(c) => std::fs::write(ctx.worktree_config(), c),
        None => {
            let _ = std::fs::remove_file(ctx.worktree_config());
            Ok(())
        }
    }
}

/// The served hostnames, sorted — the gate for a restart: DDEV derives the
/// routing rule and the certificate from them, so a restart is needed exactly
/// when this set changes.
pub fn served_hostname_set(ctx: &Ctx) -> Vec<String> {
    let mut v: Vec<String> = site::served_names(ctx)
        .iter()
        .map(|n| site::hostname_short(ctx, n))
        .collect();
    v.sort();
    v
}

/// Where DDEV's /start.sh copies the vhosts to — a COPY at container start, not
/// a mount, which is why a new vhost is visible in the container yet not live.
fn enabled_dir(ctx: &Ctx) -> PathBuf {
    PathBuf::from(if ctx.env.is_nginx() {
        "/etc/nginx/sites-enabled"
    } else {
        "/etc/apache2/sites-enabled"
    })
}

/// The container's OWN .ddev copy — never /mnt/ddev_config, the host's bind
/// mount, which on Mutagen still holds the PREVIOUS vhost until a sync back.
fn source_dir(ctx: &Ctx) -> PathBuf {
    ctx.root.join(if ctx.env.is_nginx() {
        ".ddev/nginx_full"
    } else {
        ".ddev/apache"
    })
}

/// Copy the generated vhosts into the running webserver and reload it — no
/// `ddev restart`. Validates first and leaves the running config alone when the
/// result would not load: an invalid nginx config refuses to START, taking
/// every site down.
pub fn sync_and_reload(ctx: &Ctx) -> bool {
    sync_into(ctx, &source_dir(ctx), &enabled_dir(ctx)) && valid(ctx) && reload(ctx)
}

pub fn sync_into(ctx: &Ctx, src: &std::path::Path, dst: &std::path::Path) -> bool {
    if !src.is_dir() || !dst.is_dir() {
        return false;
    }
    // Our own stale copies only: DDEV's nginx-site.conf lives here too.
    for e in std::fs::read_dir(dst).into_iter().flatten().flatten() {
        let n = e.file_name().to_string_lossy().into_owned();
        if (n.starts_with("tryout-site-") && n.ends_with(".conf"))
            || n == "tryout-server-names-hash.conf"
        {
            let _ = std::fs::remove_file(e.path());
        }
    }
    // Back per served site, by name — the markers define "served", never a
    // glob over the source, which could restore a vhost unserve just removed.
    for name in site::served_names(ctx) {
        let f = src.join(format!("tryout-site-{name}.conf"));
        if f.is_file() {
            let _ = std::fs::copy(&f, dst.join(format!("tryout-site-{name}.conf")));
        }
    }
    let hash = src.join("tryout-server-names-hash.conf");
    if hash.is_file() {
        let _ = std::fs::copy(&hash, dst.join("tryout-server-names-hash.conf"));
    }
    true
}

fn valid(ctx: &Ctx) -> bool {
    if ctx.env.is_nginx() {
        super::proc::quiet("nginx", &["-t"], None)
    } else {
        super::proc::quiet("apachectl", &["configtest"], None)
    }
}

/// Reload in place: nginx is a supervisord program with no pid file, so HUP it
/// through supervisorctl; apache reloads gracefully.
fn reload(ctx: &Ctx) -> bool {
    if ctx.env.is_nginx() {
        super::proc::quiet("supervisorctl", &["signal", "HUP", "nginx"], None)
    } else {
        super::proc::quiet("apachectl", &["-k", "graceful"], None)
    }
}

/// Apply a site config just written. A changed hostname set needs a restart
/// (DDEV owns the routing rule and the certificate), so that is false; an
/// unchanged one reloads in place.
pub fn apply_site_config(ctx: &Ctx, before: &[String]) -> bool {
    served_hostname_set(ctx) == before && ctx.in_container && sync_and_reload(ctx)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::ctx::DdevEnv;

    #[test]
    fn the_sync_clears_our_copies_but_never_ddevs_and_copies_back_by_name() {
        let d = tempfile::tempdir().unwrap();
        let ctx = Ctx::new(
            d.path(),
            DdevEnv {
                webserver_type: "nginx-fpm".into(),
                ..Default::default()
            },
        );
        let (src, dst) = (d.path().join("src"), d.path().join("dst"));
        std::fs::create_dir_all(&src).unwrap();
        std::fs::create_dir_all(&dst).unwrap();
        for f in [
            "nginx-site.conf",
            "tryout-site-gone.conf",
            "tryout-server-names-hash.conf",
        ] {
            std::fs::write(dst.join(f), "old").unwrap();
        }
        // A served site, and a vhost left in the source for one that is not.
        std::fs::create_dir_all(d.path().join("TYPO3-Instances/v13")).unwrap();
        std::fs::write(
            d.path().join("TYPO3-Instances/v13/.tryout-site"),
            "php=8.2\n",
        )
        .unwrap();
        std::fs::write(src.join("tryout-site-v13.conf"), "v13").unwrap();
        std::fs::write(src.join("tryout-site-gone.conf"), "stale").unwrap();

        assert!(sync_into(&ctx, &src, &dst));
        let mut left: Vec<String> = std::fs::read_dir(&dst)
            .unwrap()
            .flatten()
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect();
        left.sort();
        assert_eq!(left, ["nginx-site.conf", "tryout-site-v13.conf"]);
    }
}
