//! What a served site needs from the webserver: its vhost, nginx's server-name
//! hash size, and .ddev/config.worktrees.yaml (hostnames plus one FPM daemon per
//! extra PHP version).

use std::path::PathBuf;

use super::ctx::Ctx;
use super::db::{Db, Engine};
use super::kind::Mode;
use super::site;

/// Where a site's vhost goes, per webserver type. Ours carry no
/// #ddev-generated marker, so DDEV never overwrites them, and are prefixed so
/// they cannot collide with DDEV's own files.
pub fn vhost_file(ctx: &Ctx, name: &str) -> PathBuf {
    if ctx.env.is_nginx() {
        ctx.root
            .join(format!(".ddev/nginx_full/tryout-site-{name}.conf"))
    } else {
        ctx.root
            .join(format!(".ddev/apache/tryout-site-{name}.conf"))
    }
}

/// The http-level config sizing nginx's server-name hash — separate from the
/// vhosts, which are `server` blocks.
pub fn hash_config_file(ctx: &Ctx) -> PathBuf {
    ctx.root
        .join(".ddev/nginx_full/tryout-server-names-hash.conf")
}

/// Where the FPM master for a PHP version listens: DDEV's own for the project's
/// version, ours (under /run/php/, root-owned /run notwithstanding) otherwise.
pub fn fpm_socket(ctx: &Ctx, php: &str) -> String {
    if php == ctx.env.php_version {
        "/run/php-fpm.sock".into()
    } else {
        format!("/run/php/php-fpm-{php}.sock")
    }
}

/// A served site's vhost. nginx must pass `HTTPS $fcgi_https`, or PHP never
/// learns the request was TLS and TYPO3's secure session cookie never comes
/// back ("Please activate Cookies").
pub fn vhost(ctx: &Ctx, name: &str, php: &str) -> String {
    let docroot = ctx
        .in_container(&site::docroot(ctx, name))
        .display()
        .to_string();
    let host = site::hostname(ctx, name);
    let sock = fpm_socket(ctx, php);
    // Core's additional.php reads the one name; a project's app reads them all.
    let env: Vec<(&str, String)> = match ctx.mode() {
        Mode::Core => vec![("TYPO3_DB_DBNAME", site::database(name))],
        Mode::Project => site::db_env(ctx, name),
    };
    let lines =
        |f: &dyn Fn(&str, &str) -> String| -> String { env.iter().map(|(k, v)| f(k, v)).collect() };
    let fastcgi = lines(&|k, v| format!("\n        fastcgi_param {k} {v};"));
    let setenv = lines(&|k, v| format!("\n    SetEnv {k} {v}"));
    if ctx.env.is_nginx() {
        format!(
            r#"# Generated by ddev tryout worktree serve {name} — edits will be overwritten.
server {{
    listen 80;
    listen 443 ssl;
    http2 on;
    server_name {host};
    ssl_certificate /etc/ssl/certs/master.crt;
    ssl_certificate_key /etc/ssl/certs/master.key;
    root {docroot};
    index index.php index.html;

    location / {{
        try_files $uri $uri/ /index.php$is_args$args;
    }}
    location ~ [^/]\.php(/|$) {{
        try_files $uri =404;
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param TRYOUT_SITE {name};{fastcgi}
        # Without this PHP never learns the request arrived over TLS, so TYPO3
        # builds http:// URLs and its secure session cookie is never sent back —
        # the backend login then fails with "Please activate Cookies". DDEV's own
        # vhost sets the same parameter.
        fastcgi_param HTTPS $fcgi_https;
        fastcgi_pass unix:{sock};
    }}
}}
"#
        )
    } else {
        format!(
            r#"# Generated by ddev tryout worktree serve {name} — edits will be overwritten.
<VirtualHost *:80 *:443>
    ServerName {host}
    DocumentRoot {docroot}

    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/master.crt
    SSLCertificateKeyFile /etc/ssl/certs/master.key

    SetEnvIf X-Forwarded-Proto "https" HTTPS=on
    SetEnv TRYOUT_SITE {name}{setenv}

    <Directory "{docroot}/">
        AllowOverride All
        Require all granted
    </Directory>

    # Overrides the global conf-enabled/php*-fpm.conf handler: sites-enabled is
    # read later and a FilesMatch inside a VirtualHost is more specific.
    <FilesMatch ".+\.ph(?:ar|p|tml)$">
        SetHandler "proxy:unix:{sock}|fcgi://localhost"
    </FilesMatch>

    ErrorLog /dev/stdout
    CustomLog /dev/stdout combined
</VirtualHost>
"#
        )
    }
}

pub fn write_vhost(ctx: &Ctx, name: &str, php: &str) -> std::io::Result<()> {
    let file = vhost_file(ctx, name);
    std::fs::create_dir_all(file.parent().expect("a vhost file has a directory"))?;
    std::fs::write(file, vhost(ctx, name, php))
}

/// nginx refuses to START when a server_name outgrows its hash bucket — taking
/// every site down. Size the bucket for the longest served name (the short form
/// plus the `.ddev.site` DDEV appends), doubling from 64 until it clears the
/// name plus nginx's per-entry overhead. None when nothing is served.
pub fn hash_config(short_hosts: &[String]) -> Option<String> {
    let longest = short_hosts
        .iter()
        .filter(|h| !h.is_empty())
        .map(|h| h.chars().count() + 11)
        .max()?;
    let mut size = 64;
    while size < longest + 24 {
        size *= 2;
    }
    Some(format!(
        "#ddev-generated\n# Generated by ddev tryout worktree serve — do not edit.\n\
# Sized for the longest served hostname ({longest} chars). Without this nginx\n\
# refuses to start once a name outgrows the default bucket, taking every site\n\
# with it.\nserver_names_hash_bucket_size {size};\n"
    ))
}

/// .ddev/config.worktrees.yaml for the served sites: their hostnames (so mkcert
/// covers them) and one FPM daemon per PHP version other than the project's.
/// None when nothing is served.
pub fn worktree_config(ctx: &Ctx) -> Option<String> {
    let names = site::served_names(ctx);
    if names.is_empty() {
        return None;
    }
    let mut s = String::from(
        "#ddev-silent-no-warn\n# Generated by ddev tryout worktree serve — do not edit.\n\
# Hostnames must be registered here so mkcert includes them in the cert.\n\nadditional_hostnames:\n",
    );
    for n in &names {
        s.push_str(&format!("  - {}\n", site::hostname_short(ctx, n)));
    }
    let mut phps: Vec<String> = names
        .iter()
        .map(|n| site::php_version(ctx, n))
        .filter(|p| !p.is_empty() && *p != ctx.env.php_version)
        .collect();
    phps.sort();
    phps.dedup();
    if !phps.is_empty() {
        s.push_str("\nweb_extra_daemons:\n");
        for v in phps {
            s.push_str(&format!(
                "  - name: tryout-php-{v}\n    command: \"/var/www/html/.ddev/tryout/tryout __fpm {v}\"\n    directory: /var/www/html\n"
            ));
        }
    }
    Some(s)
}

/// .ddev/docker-compose.tryout-db.yaml: one service per database server a
/// served site runs on besides the project's own — a type at a version —
/// reached by the web container under the service's name, with DDEV's own
/// credentials. Its data lives in a named volume of its own, so a database kept
/// by `unserve` is there again when a site returns. None when no site needs one.
///
/// A server stays while a site runs on it or a database `unserve` kept is on
/// it: `ddev delete` removes the volumes of the servers it runs, and only
/// those, so a server dropped with data still in it would leave its volume to
/// the next project that happens to get the same name.
pub fn db_services_compose(dbs: &[Db]) -> Option<String> {
    let servers: Vec<&Db> = dbs.iter().filter(|d| d.service().is_some()).collect();
    if servers.is_empty() {
        return None;
    }
    let mut s = String::from(
        "#ddev-generated\n# Generated by ddev tryout worktree serve --db — do not edit.\n\
# The database servers served sites run on besides the project's own.\n\nservices:\n",
    );
    for d in &servers {
        let (Some(svc), Some(image)) = (d.service(), d.image()) else {
            continue;
        };
        let (env, health, command) = match d.engine {
            Engine::Postgres => (
                "      POSTGRES_USER: db\n      POSTGRES_PASSWORD: db\n      POSTGRES_DB: db\n",
                "[\"CMD-SHELL\", \"pg_isready -U db\"]",
                String::new(),
            ),
            Engine::Mariadb => (
                "      MARIADB_ROOT_PASSWORD: root\n      MARIADB_USER: db\n      MARIADB_PASSWORD: db\n      MARIADB_DATABASE: db\n",
                "[\"CMD\", \"healthcheck.sh\", \"--connect\", \"--innodb_initialized\"]",
                String::new(),
            ),
            // The web image's client is MariaDB's, which cannot log in with
            // MySQL 8's default caching_sha2_password: native passwords, turned
            // on the way each version takes it.
            Engine::Mysql => (
                "      MYSQL_ROOT_PASSWORD: root\n      MYSQL_USER: db\n      MYSQL_PASSWORD: db\n      MYSQL_DATABASE: db\n",
                "[\"CMD\", \"mysqladmin\", \"ping\", \"-uroot\", \"-proot\"]",
                if d.version.starts_with("8.0") {
                    "    command: --default-authentication-plugin=mysql_native_password\n".into()
                } else {
                    "    command: --mysql-native-password=ON --authentication-policy=mysql_native_password\n".into()
                },
            ),
            Engine::Sqlite => continue,
        };
        let data = d.data_dir();
        s.push_str(&format!(
            "  {svc}:\n    container_name: ddev-${{DDEV_SITENAME}}-{svc}\n    image: {image}\n{command}    labels:\n      com.ddev.site-name: ${{DDEV_SITENAME}}\n      com.ddev.approot: ${{DDEV_APPROOT}}\n    environment:\n{env}    volumes:\n      - {svc}:{data}\n    healthcheck:\n      test: {health}\n      interval: 2s\n      retries: 60\n",
        ));
    }
    s.push_str("\nvolumes:\n");
    for svc in servers.iter().filter_map(|d| d.service()) {
        s.push_str(&format!(
            "  {svc}:\n    name: ddev-${{DDEV_SITENAME}}-{svc}\n"
        ));
    }
    Some(s)
}

/// The extra database servers the compose file declares — what DDEV runs once
/// it has restarted.
pub fn declared_db_services(ctx: &Ctx) -> Vec<Db> {
    let text = std::fs::read_to_string(ctx.db_services_file()).unwrap_or_default();
    Db::choices()
        .into_iter()
        .filter(|d| {
            d.service()
                .is_some_and(|svc| text.contains(&format!("\n  {svc}:\n    container_name:")))
        })
        .collect()
}

/// Write the compose file for these servers, or remove it when there are none.
pub fn write_db_services(ctx: &Ctx, dbs: &[Db]) -> std::io::Result<()> {
    match db_services_compose(dbs) {
        Some(c) => std::fs::write(ctx.db_services_file(), c),
        None => {
            let _ = std::fs::remove_file(ctx.db_services_file());
            Ok(())
        }
    }
}

/// Rewrite config.worktrees.yaml, the hash config and the database services
/// from what is served now; all go when nothing is.
pub fn write_worktree_config(ctx: &Ctx) -> std::io::Result<()> {
    let hosts: Vec<String> = site::served_names(ctx)
        .iter()
        .map(|n| site::hostname_short(ctx, n))
        .collect();
    let hash = hash_config_file(ctx);
    match hash_config(&hosts) {
        Some(c) => {
            std::fs::create_dir_all(hash.parent().expect("has a directory"))?;
            std::fs::write(&hash, c)?;
        }
        None => {
            let _ = std::fs::remove_file(&hash);
        }
    }
    write_db_services(ctx, &site::extra_dbs(ctx))?;
    match worktree_config(ctx) {
        Some(c) => std::fs::write(ctx.worktree_config(), c),
        None => {
            let _ = std::fs::remove_file(ctx.worktree_config());
            Ok(())
        }
    }
}

/// What DDEV only takes up on a restart: the served hostnames (it derives the
/// routing rule and the certificate from them) and the extra database
/// services. A restart is needed exactly when this changes.
pub fn restart_key(ctx: &Ctx) -> Vec<String> {
    let mut v: Vec<String> = site::served_names(ctx)
        .iter()
        .map(|n| site::hostname_short(ctx, n))
        .collect();
    v.sort();
    v.extend(
        declared_db_services(ctx)
            .into_iter()
            .filter_map(|d| d.service())
            .map(|svc| format!("service {svc}")),
    );
    v
}

/// Where DDEV's /start.sh copies the vhosts to — a COPY at container start, not
/// a mount, which is why a new vhost is visible in the container yet not live.
fn enabled_dir(ctx: &Ctx) -> PathBuf {
    PathBuf::from(if ctx.env.is_nginx() {
        "/etc/nginx/sites-enabled"
    } else {
        "/etc/apache2/sites-enabled"
    })
}

/// The container's OWN .ddev copy — never /mnt/ddev_config, the host's bind
/// mount, which on Mutagen still holds the PREVIOUS vhost until a sync back.
fn source_dir(ctx: &Ctx) -> PathBuf {
    ctx.root.join(if ctx.env.is_nginx() {
        ".ddev/nginx_full"
    } else {
        ".ddev/apache"
    })
}

/// Copy the generated vhosts into the running webserver and reload it — no
/// `ddev restart`. Validates first and leaves the running config alone when the
/// result would not load: an invalid nginx config refuses to START, taking
/// every site down.
pub fn sync_and_reload(ctx: &Ctx) -> bool {
    sync_into(ctx, &source_dir(ctx), &enabled_dir(ctx)) && valid(ctx) && reload(ctx)
}

pub fn sync_into(ctx: &Ctx, src: &std::path::Path, dst: &std::path::Path) -> bool {
    if !src.is_dir() || !dst.is_dir() {
        return false;
    }
    // Our own stale copies only: DDEV's nginx-site.conf lives here too.
    for e in std::fs::read_dir(dst).into_iter().flatten().flatten() {
        let n = e.file_name().to_string_lossy().into_owned();
        if (n.starts_with("tryout-site-") && n.ends_with(".conf"))
            || n == "tryout-server-names-hash.conf"
        {
            let _ = std::fs::remove_file(e.path());
        }
    }
    // Back per served site, by name — the markers define "served", never a
    // glob over the source, which could restore a vhost unserve just removed.
    for name in site::served_names(ctx) {
        let f = src.join(format!("tryout-site-{name}.conf"));
        if f.is_file() {
            let _ = std::fs::copy(&f, dst.join(format!("tryout-site-{name}.conf")));
        }
    }
    let hash = src.join("tryout-server-names-hash.conf");
    if hash.is_file() {
        let _ = std::fs::copy(&hash, dst.join("tryout-server-names-hash.conf"));
    }
    true
}

fn valid(ctx: &Ctx) -> bool {
    if ctx.env.is_nginx() {
        super::proc::quiet("nginx", &["-t"], None)
    } else {
        super::proc::quiet("apachectl", &["configtest"], None)
    }
}

/// Reload in place: nginx is a supervisord program with no pid file, so HUP it
/// through supervisorctl; apache reloads gracefully.
fn reload(ctx: &Ctx) -> bool {
    if ctx.env.is_nginx() {
        super::proc::quiet("supervisorctl", &["signal", "HUP", "nginx"], None)
    } else {
        super::proc::quiet("apachectl", &["-k", "graceful"], None)
    }
}

/// Apply a site config just written. A changed hostname set needs a restart
/// (DDEV owns the routing rule and the certificate), so that is false; an
/// unchanged one reloads in place.
pub fn apply_site_config(ctx: &Ctx, before: &[String]) -> bool {
    restart_key(ctx) == before && ctx.in_container && sync_and_reload(ctx)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::ctx::DdevEnv;

    #[test]
    fn a_project_vhost_serves_the_worktrees_docroot_and_hands_over_its_database() {
        let d = crate::core::ctx::tests::project_repo();
        for (server, env_line) in [
            (
                "nginx-fpm",
                "        fastcgi_param TRYOUT_DB_NAME db_feat;\n",
            ),
            ("apache-fpm", "    SetEnv TRYOUT_DB_NAME db_feat\n"),
        ] {
            let c = Ctx::new(
                d.path(),
                DdevEnv {
                    webserver_type: server.into(),
                    sitename: "shop".into(),
                    docroot: "public".into(),
                    database: "mariadb:11.8".into(),
                    ..Default::default()
                },
            );
            site::write_marker(&c, "feat", "8.4", &Db::of_project(&c)).unwrap();
            let v = vhost(&c, "feat", "8.4");
            assert!(v.contains(env_line), "{server}: {v}");
            assert!(v.contains("/var/www/html/worktrees/feat/public"), "{v}");
            assert!(v.contains("feat.shop.ddev.site"), "{v}");
            assert!(!v.contains("TYPO3_DB_DBNAME"), "{v}");
        }
    }

    #[test]
    fn the_sync_clears_our_copies_but_never_ddevs_and_copies_back_by_name() {
        let d = tempfile::tempdir().unwrap();
        let ctx = Ctx::new(
            d.path(),
            DdevEnv {
                webserver_type: "nginx-fpm".into(),
                ..Default::default()
            },
        );
        let (src, dst) = (d.path().join("src"), d.path().join("dst"));
        std::fs::create_dir_all(&src).unwrap();
        std::fs::create_dir_all(&dst).unwrap();
        for f in [
            "nginx-site.conf",
            "tryout-site-gone.conf",
            "tryout-server-names-hash.conf",
        ] {
            std::fs::write(dst.join(f), "old").unwrap();
        }
        // A served site, and a vhost left in the source for one that is not.
        std::fs::create_dir_all(d.path().join("TYPO3-Instances/v13")).unwrap();
        std::fs::write(
            d.path().join("TYPO3-Instances/v13/.tryout-site"),
            "php=8.2\n",
        )
        .unwrap();
        std::fs::write(src.join("tryout-site-v13.conf"), "v13").unwrap();
        std::fs::write(src.join("tryout-site-gone.conf"), "stale").unwrap();

        assert!(sync_into(&ctx, &src, &dst));
        let mut left: Vec<String> = std::fs::read_dir(&dst)
            .unwrap()
            .flatten()
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect();
        left.sort();
        assert_eq!(left, ["nginx-site.conf", "tryout-site-v13.conf"]);
    }
}
